#include <stdio.h>
#include <stdlib.h>
#include <sys/types.h>

int checkP2(int x);
int *dTob(int n,int l);
int bTod(int a[],int l);

int main(){
int pgs=4; //page size
int ms=32; //memory size
int nof=ms/pgs; //number of frames
int offset_bit; //find out # of bits required for offset
int m; //find out address spaces required in main memory
int pg_num_bit; ////find out # of bits required for page number
int la[]={8,4,3,2,15,18,25}; //logical addresses generated by the CPU
int pmt[]={3,6,8,12,2}; //page table
/*
find out corresponding physical addresses of generated logical
addresses
using the formula: physical address = (frame # * page
size)+offset
*/
//Do your code here
  
    printf("Page size: %d\n", pgs);
    printf("Memory size: %d\n", ms);
    printf("Number of frames required: %d\n", nof);
  
    m = checkP2(ms);
    offset_bit = checkP2(pgs);
    pg_num_bit = m - offset_bit; 
  
    printf("Page number bits: %d\n", pg_num_bit);
    printf("Offset bits: %d\n", offset_bit);
    printf("Number of address spaces: %d\n", m);
    printf("Page Table_____\n");

    int size_of_table = sizeof(pmt) / sizeof(pmt[0]);
    for (int i = 0; i < size_of_table; i++) {
        printf("%d -> %d\n", i, pmt[i]);
    }
    
    int size_of_la = sizeof(la) / sizeof(la[0]);
    for (int i = 0; i < size_of_la; i++){
        int *la_in_binary = dTob(la[i],m);
        int* pageno = (int*)malloc(pg_num_bit * sizeof(int));
        int* offset = (int*)malloc(offset_bit * sizeof(int));
      
        for (int i = 0; i < pg_num_bit; i++){
          pageno[i] = la_in_binary[i];
        }
        for (int i = pg_num_bit; i < m; i++){
          offset[i - pg_num_bit] = la_in_binary[i];
        }

       int pagno_in_dec = bTod(pageno,pg_num_bit);
       int offset_in_dec =  bTod(offset,offset_bit);
       int fn = pmt[pagno_in_dec];
       int pa = (fn * pgs) + offset_in_dec;
      
       if (pagno_in_dec > (size_of_table - 1) ){
         printf("%d is an invalid page number\n", pagno_in_dec);
       }
       else if((pa >= 0) && (pa <= (ms - 1))){
         printf("Corresponding physical address of logical address %d: %d\n", la[i], pa);
       }
       else if (pa > (ms - 1)){
        printf("%d is an invalid physical address\n", pa);
      }
    }  
  
return 0;
}

int checkP2(int x){
//Do your code here
    int power = 0;
        if (x % 2 == 0){
          while (x > 1){
          x = x / 2;
          power++;
        }
      }
        else{
          power = -1;
    }
return power;
}

int *dTob(int n,int l){
//Do your code here
int *store = malloc(l * sizeof(int));
for (int i = l - 1; i >= 0; i--) {
        store[i] = n % 2;
        n = n / 2;
    }
return store;
}

int bTod(int a[],int l){
//Do your code here
    int dec_value = 0;
    int power = 1;
    for (int i = l - 1; i >= 0; i--) {
        dec_value += a[i] * power;
        power = power * 2;
    }
  return dec_value;
}